package helpers

import (
	"github.com/RenaLio/tudou/pkg/provider/translator/models/claude"
	"github.com/RenaLio/tudou/pkg/provider/translator/models/openai"
	"github.com/goccy/go-json"
)

// ToolCalls: The tool calls generated by the model, such as function calls.

// openAI ToolCalls
// - chatCompletionMessageFunctionToolCall(openai.ChatMessageToolCall),type:function
// - ChatCompletionMessageCustomToolCall(openai.ChatMessageToolCall),type:custom
var _ = openai.ChatMessageToolCall{}

// openAI response ToolCalls
// - FunctionCall
// - CustomToolCall
// - FileSearchCall(openai.FileSearchCall)
// - ComputerCall
// - WebSearchCall
// - ToolSearchCall
// - ImageGenerationCall
// - CodeInterpreterCall
// - LocalShellCall
// - ShellCall
// - ApplyPatchCall
// - McpCall
var _ = openai.Response{}
var _ = openai.ResponseFunctionCall{}

// claude ToolCalls
// - ToolUseBlockParam
// - ServerToolUseBlockParam name:"web_search","web_fetch","code_execution","bash_code_execution","text_editor_code_execution","tool_search_tool_regex","tool_search_tool_bm25"
var _ = claude.ToolUseBlock{}
var _ = claude.CreateMessageRequest{}

// ChatMessageToolCallToClaudeToolUse converts OpenAI Chat Completions tool call to Claude ToolUseBlock JSON
// Parameter:
//   - in - The ChatMessageToolCall from Chat Completions API
//
// Returns:
//   - json.RawMessage - The ToolUseBlock JSON for Claude API
//
// Note:
//   - Only supports type="function" tool calls (Claude doesn't have "custom" tool calls)
//   - Arguments are parsed as JSON and converted to map[string]json.RawMessage format
//   - Returns nil for unsupported types
func ChatMessageToolCallToClaudeToolUse(in *openai.ChatMessageToolCall) json.RawMessage {
	if in == nil || in.Type != "function" || in.Function == nil {
		return nil
	}

	// Parse arguments JSON string into map
	var inputMap map[string]json.RawMessage
	if err := json.Unmarshal([]byte(in.Function.Arguments), &inputMap); err != nil {
		// If parsing fails, store the entire arguments as a JSON string
		escapedArgs, _ := json.Marshal(in.Function.Arguments)
		inputMap = map[string]json.RawMessage{
			"arguments": escapedArgs,
		}
		return nil
	}

	resp := claude.ToolUseBlockParam{
		Type:  "tool_use",
		ID:    in.Id,
		Name:  in.Function.Name,
		Input: inputMap,
	}
	data, _ := json.Marshal(resp)
	return data
}

// ClaudeToolUseToChatMessageToolCall converts Claude ToolUseBlock JSON to OpenAI Chat Completions tool call
// Parameter:
//   - in - The JSON raw message of ToolUseBlock from Claude API
//
// Returns:
//   - The ChatMessageToolCall for Chat Completions API
//
// Note:
//   - Always returns type="function" (Claude doesn't distinguish between function and custom tool calls)
//   - Input map is marshaled to JSON string for the Arguments field
//   - Returns nil for nil input or unsupported types
func ClaudeToolUseToChatMessageToolCall(in json.RawMessage) *openai.ChatMessageToolCall {
	if in == nil {
		return nil
	}

	switch getType(in) {
	case "tool_use":
		var resp claude.ToolUseBlockParam
		if err := json.Unmarshal(in, &resp); err != nil {
			return nil
		}
		// Marshal input map to JSON string
		arguments, err := json.Marshal(resp.Input)
		if err != nil {
			arguments = []byte("{}")
		}
		return &openai.ChatMessageToolCall{
			Id:   resp.ID,
			Type: "function",
			Function: &openai.ChatMessageToolCallFunction{
				Name:      resp.Name,
				Arguments: string(arguments),
			},
		}
	}
	return nil
}

// ClaudeToolUseToResponseToolCall converts Claude ToolUseBlock JSON to OpenAI Responses API tool call
// Parameter:
//   - in - The JSON raw message of ToolUseBlock from Claude API
//
// Returns:
//   - json.RawMessage - The ResponseFunctionCall JSON for Responses API
//
// Note:
//   - Only supports "tool_use" type (Claude's tool call type)
//   - Claude's input map is marshaled to JSON string for the Arguments field
//   - Returns nil for unsupported types or nil input
func ClaudeToolUseToResponseToolCall(in json.RawMessage) json.RawMessage {
	if in == nil {
		return nil
	}

	switch getType(in) {
	case "tool_use":
		var resp claude.ToolUseBlockParam
		if err := json.Unmarshal(in, &resp); err != nil {
			return nil
		}
		// Marshal input map to JSON string for arguments
		arguments, err := json.Marshal(resp.Input)
		if err != nil {
			arguments = []byte("{}")
		}
		response := openai.ResponseFunctionCall{
			Type:      "function_call",
			Arguments: string(arguments),
			CallID:    resp.ID,
			Name:      resp.Name,
			//Id:        resp.ID,
			Status: "completed",
		}
		data, _ := json.Marshal(response)
		return data
	case "server_tool_use":
		switch getName(in) {
		case "web_search":
			return nil
		case "web_fetch":
			return nil
		case "code_execution":
			return nil
		case "bash_code_execution":
			return nil
		case "text_editor_code_execution":
			return nil
		case "tool_search_tool_regex":
			return nil
		case "tool_search_tool_bm25":
			return nil
		}
	}
	return nil
}

// ResponseToolCallToClaudeToolUse converts OpenAI Responses API tool call to Claude ToolUseBlock JSON
// Parameter:
//   - in - The JSON raw message of ResponseFunctionCall from Responses API
//
// Returns:
//   - json.RawMessage - The ToolUseBlock JSON for Claude API
//
// Note:
//   - Only supports "function_call" type (Responses API's tool call type)
//   - Arguments JSON string is parsed into map[string]json.RawMessage for Claude's input field
//   - Returns nil for unsupported types (e.g., "custom_tool_call") or nil input
func ResponseToolCallToClaudeToolUse(in json.RawMessage) json.RawMessage {
	if in == nil {
		return nil
	}

	switch getType(in) {
	case "function_call":
		var resp openai.ResponseFunctionCall
		if err := json.Unmarshal(in, &resp); err != nil {
			return nil
		}
		// Parse arguments JSON string into map for Claude's input field
		var inputMap map[string]json.RawMessage
		if err := json.Unmarshal([]byte(resp.Arguments), &inputMap); err != nil {
			// If parsing fails, store the entire arguments as a JSON string
			//escapedArgs, _ := json.Marshal(resp.Arguments)
			//inputMap = map[string]json.RawMessage{
			//	"arguments": escapedArgs,
			//}
			return nil
		}
		claudeResp := claude.ToolUseBlockParam{
			Type:  "tool_use",
			ID:    resp.CallID,
			Name:  resp.Name,
			Input: inputMap,
		}
		data, _ := json.Marshal(claudeResp)
		return data
	case "custom_tool_call":
		return nil
	case "tool_search_call":
		return nil
	case "web_search_call":
		return nil
	case "shell_call":
		return nil
	case "code_interpreter_call":
		return nil
	}
	return nil
}

// ResponseToolCallToChatMessageToolCall converts Responses API tool call to Chat Completions API tool call
// Parameter:
//   - in - The JSON raw message of ResponseFunctionCall or ResponseCustomToolCall
//
// Returns:
//   - The ChatMessageToolCall for Chat Completions API
//
// Note:
//   - Supports "function_call" and "custom_tool_call" types
//   - Returns nil for unsupported types
func ResponseToolCallToChatMessageToolCall(in json.RawMessage) *openai.ChatMessageToolCall {
	if in == nil {
		return nil
	}
	switch getType(in) {
	case "function_call":
		var resp openai.ResponseFunctionCall
		if err := json.Unmarshal(in, &resp); err != nil {
			return nil
		}
		return &openai.ChatMessageToolCall{
			Id:   resp.CallID,
			Type: "function",
			Function: &openai.ChatMessageToolCallFunction{
				Name:      resp.Name,
				Arguments: resp.Arguments,
			},
		}
	case "custom_tool_call":
		var resp openai.ResponseCustomToolCall
		if err := json.Unmarshal(in, &resp); err != nil {
			return nil
		}
		return &openai.ChatMessageToolCall{
			Id:   resp.CallId,
			Type: "custom",
			Custom: &openai.ChatMessageToolCallCustom{
				Name:  resp.Name,
				Input: resp.Input,
			},
		}
	}
	return nil
}

// ChatMessageToolCallToResponseToolCall converts Responses API tool call to Chat Completions API tool call
// Parameter:
//   - in - The ChatMessageToolCall from Chat Completions API
//
// Returns:
//   - json.RawMessage - The ResponseToolCall for Responses API
//
// Note:
//   - Supports "function" and "custom" types
//   - Returns nil for unsupported types
func ChatMessageToolCallToResponseToolCall(in *openai.ChatMessageToolCall) json.RawMessage {
	if in == nil {
		return nil
	}
	switch in.Type {
	case "function":
		resp := new(openai.ResponseFunctionCall)
		resp.Type = "function_call"
		resp.Arguments = in.Function.Arguments
		resp.CallID = in.Id
		resp.Name = in.Function.Name
		data, _ := json.Marshal(resp)
		return data
	case "custom":
		resp := new(openai.ResponseCustomToolCall)
		resp.Type = "custom_tool_call"
		resp.CallId = in.Id
		resp.Input = in.Custom.Input
		resp.Name = in.Custom.Name
		data, _ := json.Marshal(resp)
		return data
	}
	return nil
}
