// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/RenaLio/tudou/internal/config"
	"github.com/RenaLio/tudou/internal/handler"
	"github.com/RenaLio/tudou/internal/pkg/app"
	"github.com/RenaLio/tudou/internal/pkg/jwt"
	"github.com/RenaLio/tudou/internal/pkg/log"
	"github.com/RenaLio/tudou/internal/pkg/server/http"
	"github.com/RenaLio/tudou/internal/pkg/sid"
	"github.com/RenaLio/tudou/internal/repository"
	"github.com/RenaLio/tudou/internal/router"
	"github.com/RenaLio/tudou/internal/server"
	"github.com/RenaLio/tudou/internal/service"
	"github.com/RenaLio/tudou/internal/start"
	"github.com/google/wire"
)

// Injectors from wire.go:

func BuildApp(configConfig *config.Config, logger *log.Logger) (*app.App, func(), error) {
	sidSid := sid.NewSid(configConfig)
	jsonCache := repository.NewCache(configConfig, logger)
	jwtJWT := jwt.NewJwt(configConfig)
	db := repository.NewDB(configConfig, logger)
	repositoryRepository := repository.NewRepository(logger, db, jsonCache, sidSid)
	transaction := repository.NewTransaction(repositoryRepository)
	serviceService := service.NewService(logger, sidSid, jsonCache, jwtJWT, transaction)
	handlerHandler := handler.NewHandler(logger, serviceService)
	aiModelRepo := repository.NewAIModelRepo(repositoryRepository)
	aiModelService := service.NewAIModelService(serviceService, aiModelRepo)
	modelHandler := handler.NewModelHandler(handlerHandler, aiModelService)
	channelRepo := repository.NewChannelRepo(repositoryRepository)
	channelService := service.NewChannelService(serviceService, channelRepo, aiModelRepo)
	relayService := service.NewRelayService(serviceService)
	channelHandler := handler.NewChannelHandler(handlerHandler, channelService, relayService)
	channelGroupRepo := repository.NewChannelGroupRepo(repositoryRepository)
	channelGroupService := service.NewChannelGroupService(serviceService, channelGroupRepo)
	channelGroupHandler := handler.NewChannelGroupHandler(handlerHandler, channelGroupService)
	tokenRepo := repository.NewTokenRepo(repositoryRepository)
	tokenService := service.NewTokenService(serviceService, tokenRepo)
	tokenHandler := handler.NewTokenHandler(handlerHandler, tokenService)
	userRepo := repository.NewUserRepo(repositoryRepository)
	userService := service.NewUserService(serviceService, userRepo)
	userHandler := handler.NewUserHandler(handlerHandler, userService)
	systemConfigRepo := repository.NewSystemConfigRepo(repositoryRepository)
	systemConfigService := service.NewSystemConfigService(serviceService, systemConfigRepo)
	systemConfigHandler := handler.NewSystemConfigHandler(handlerHandler, systemConfigService)
	deps := &router.Deps{
		Conf:                configConfig,
		Logger:              logger,
		ModelHandler:        modelHandler,
		ChannelHandler:      channelHandler,
		ChannelGroupHandler: channelGroupHandler,
		TokenHandler:        tokenHandler,
		UserHandler:         userHandler,
		SystemConfigHandler: systemConfigHandler,
	}
	httpServer := server.NewHttpServer(deps)
	appApp := newApp(httpServer)
	return appApp, func() {
	}, nil
}

func InitApp(configConfig *config.Config, logger *log.Logger) error {
	db := repository.NewDB(configConfig, logger)
	migrate := server.NewMigrate(db, logger)
	sidSid := sid.NewSid(configConfig)
	jsonCache := repository.NewCache(configConfig, logger)
	jwtJWT := jwt.NewJwt(configConfig)
	repositoryRepository := repository.NewRepository(logger, db, jsonCache, sidSid)
	transaction := repository.NewTransaction(repositoryRepository)
	serviceService := service.NewService(logger, sidSid, jsonCache, jwtJWT, transaction)
	userRepo := repository.NewUserRepo(repositoryRepository)
	userService := service.NewUserService(serviceService, userRepo)
	channelGroupRepo := repository.NewChannelGroupRepo(repositoryRepository)
	channelGroupService := service.NewChannelGroupService(serviceService, channelGroupRepo)
	error2 := start.InitApp(migrate, userService, channelGroupService)
	return error2
}

// wire.go:

var repositorySet = wire.NewSet(repository.NewDB, repository.NewCache, repository.NewRepository, repository.NewTransaction, repository.NewAIModelRepo, repository.NewChannelRepo, repository.NewChannelGroupRepo, repository.NewTokenRepo, repository.NewUserRepo, repository.NewSystemConfigRepo)

var depsSet = wire.NewSet(jwt.NewJwt, sid.NewSid)

var serviceSet = wire.NewSet(service.NewService, service.NewAIModelService, service.NewChannelService, service.NewChannelGroupService, service.NewTokenService, service.NewUserService, service.NewSystemConfigService, service.NewRelayService)

var handlerSet = wire.NewSet(handler.NewHandler, handler.NewModelHandler, handler.NewChannelHandler, handler.NewChannelGroupHandler, handler.NewTokenHandler, handler.NewUserHandler, handler.NewSystemConfigHandler)

var serverSet = wire.NewSet(server.NewHttpServer, server.NewMigrate)

func newApp(httpServer *http.Server) *app.App {
	return app.NewApp(app.WithServer(httpServer), app.WithName("tudou"))
}
