// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/RenaLio/tudou/internal/config"
	"github.com/RenaLio/tudou/internal/handler"
	"github.com/RenaLio/tudou/internal/loadbalancer"
	"github.com/RenaLio/tudou/internal/pkg/app"
	"github.com/RenaLio/tudou/internal/pkg/jwt"
	"github.com/RenaLio/tudou/internal/pkg/log"
	"github.com/RenaLio/tudou/internal/pkg/server/http"
	"github.com/RenaLio/tudou/internal/pkg/sid"
	"github.com/RenaLio/tudou/internal/repository"
	"github.com/RenaLio/tudou/internal/router"
	"github.com/RenaLio/tudou/internal/server"
	"github.com/RenaLio/tudou/internal/server/task"
	"github.com/RenaLio/tudou/internal/service"
	"github.com/RenaLio/tudou/internal/start"
	"github.com/RenaLio/tudou/internal/tasks"
	"github.com/google/wire"
)

// Injectors from wire.go:

func BuildApp(configConfig *config.Config, logger *log.Logger) (*app.App, func(), error) {
	sidSid := sid.NewSid(configConfig)
	jsonCache := repository.NewCache(configConfig, logger)
	jwtJWT := jwt.NewJwt(configConfig)
	db := repository.NewDB(configConfig, logger)
	repositoryRepository := repository.NewRepository(logger, db, jsonCache, sidSid)
	transaction := repository.NewTransaction(repositoryRepository)
	serviceService := service.NewService(logger, sidSid, jsonCache, jwtJWT, transaction)
	handlerHandler := handler.NewHandler(logger, serviceService)
	aiModelRepo := repository.NewAIModelRepo(repositoryRepository)
	aiModelService := service.NewAIModelService(serviceService, aiModelRepo)
	modelHandler := handler.NewModelHandler(handlerHandler, aiModelService)
	channelRepo := repository.NewChannelRepo(repositoryRepository)
	channelGroupRepo := repository.NewChannelGroupRepo(repositoryRepository)
	registry := start.InitLBRegistry(db, channelGroupRepo)
	channelService := service.NewChannelService(serviceService, channelRepo, aiModelRepo, registry, channelGroupRepo)
	dynamicLoadBalancer := loadbalancer.NewDynamicLoadBalancer(registry)
	asyncMetricsCollector := newAsyncMetricsCollector(registry)
	requestLogRepo := repository.NewRequestLogRepo(repositoryRepository)
	requestLogServiceImpl := service.NewRequestLogService(serviceService, requestLogRepo)
	relayService := service.NewRelayService(serviceService, dynamicLoadBalancer, asyncMetricsCollector, aiModelRepo, requestLogServiceImpl)
	channelHandler := handler.NewChannelHandler(handlerHandler, channelService, relayService)
	channelGroupService := service.NewChannelGroupService(serviceService, channelGroupRepo, registry)
	channelGroupHandler := handler.NewChannelGroupHandler(handlerHandler, channelGroupService)
	tokenRepo := repository.NewTokenRepo(repositoryRepository)
	tokenService := service.NewTokenService(serviceService, tokenRepo)
	tokenHandler := handler.NewTokenHandler(handlerHandler, tokenService)
	userRepo := repository.NewUserRepo(repositoryRepository)
	userService := service.NewUserService(serviceService, userRepo)
	userHandler := handler.NewUserHandler(handlerHandler, userService)
	systemConfigRepo := repository.NewSystemConfigRepo(repositoryRepository)
	systemConfigService := service.NewSystemConfigService(serviceService, systemConfigRepo)
	systemConfigHandler := handler.NewSystemConfigHandler(handlerHandler, systemConfigService)
	channelStatsRepo := repository.NewChannelStatsRepo(repositoryRepository)
	channelModelStatsRepo := repository.NewChannelModelStatsRepo(repositoryRepository)
	tokenStatsRepo := repository.NewTokenStatsRepo(repositoryRepository)
	userStatsRepo := repository.NewUserStatsRepo(repositoryRepository)
	userUsageDailyStatsRepo := repository.NewUserUsageDailyStatsRepo(repositoryRepository)
	userUsageHourlyStatsRepo := repository.NewUserUsageHourlyStatsRepo(repositoryRepository)
	statsService := service.NewStatsService(serviceService, channelStatsRepo, channelModelStatsRepo, tokenStatsRepo, userStatsRepo, userUsageDailyStatsRepo, userUsageHourlyStatsRepo)
	statsHandler := handler.NewStatsHandler(handlerHandler, statsService)
	relayHandler := handler.NewRelayHandler(handlerHandler, relayService)
	requestLogHandler := handler.NewRequestLogHandler(handlerHandler, requestLogServiceImpl)
	debugHelperHandler := handler.NewDebugHelperHandler(handlerHandler, registry)
	deps := &router.Deps{
		Conf:                configConfig,
		Logger:              logger,
		ModelHandler:        modelHandler,
		ChannelHandler:      channelHandler,
		ChannelGroupHandler: channelGroupHandler,
		TokenHandler:        tokenHandler,
		UserHandler:         userHandler,
		SystemConfigHandler: systemConfigHandler,
		StatsHandler:        statsHandler,
		RelayHandler:        relayHandler,
		RequestLogHandler:   requestLogHandler,
		DebugHandler:        debugHelperHandler,
		TokenService:        tokenService,
		DB:                  db,
		Registry:            registry,
	}
	httpServer := server.NewHttpServer(deps)
	mockTask := tasks.NewMockTask(logger)
	aggregationTaskRepo := repository.NewAggregationTaskRepo(repositoryRepository)
	statsAggregationTask := tasks.NewStatsAggregationTask(logger, sidSid, transaction, aggregationTaskRepo, requestLogRepo, channelStatsRepo, channelModelStatsRepo, tokenStatsRepo, userStatsRepo, userUsageDailyStatsRepo, userUsageHourlyStatsRepo)
	taskServer := NewTaskServer(logger, mockTask, statsAggregationTask)
	appApp := newApp(httpServer, taskServer)
	return appApp, func() {
	}, nil
}

func InitApp(configConfig *config.Config, logger *log.Logger) error {
	db := repository.NewDB(configConfig, logger)
	migrate := server.NewMigrate(db, logger)
	sidSid := sid.NewSid(configConfig)
	jsonCache := repository.NewCache(configConfig, logger)
	jwtJWT := jwt.NewJwt(configConfig)
	repositoryRepository := repository.NewRepository(logger, db, jsonCache, sidSid)
	transaction := repository.NewTransaction(repositoryRepository)
	serviceService := service.NewService(logger, sidSid, jsonCache, jwtJWT, transaction)
	userRepo := repository.NewUserRepo(repositoryRepository)
	userService := service.NewUserService(serviceService, userRepo)
	channelGroupRepo := repository.NewChannelGroupRepo(repositoryRepository)
	registry := start.InitLBRegistry(db, channelGroupRepo)
	channelGroupService := service.NewChannelGroupService(serviceService, channelGroupRepo, registry)
	error2 := start.InitApp(migrate, userService, channelGroupService)
	return error2
}

// wire.go:

var repositorySet = wire.NewSet(repository.NewDB, repository.NewCache, repository.NewRepository, repository.NewTransaction, repository.NewAIModelRepo, repository.NewChannelRepo, repository.NewChannelGroupRepo, repository.NewTokenRepo, repository.NewChannelStatsRepo, repository.NewChannelModelStatsRepo, repository.NewTokenStatsRepo, repository.NewUserStatsRepo, repository.NewUserUsageDailyStatsRepo, repository.NewUserUsageHourlyStatsRepo, repository.NewRequestLogRepo, repository.NewAggregationTaskRepo, repository.NewUserRepo, repository.NewSystemConfigRepo)

var depsSet = wire.NewSet(jwt.NewJwt, sid.NewSid, start.InitLBRegistry, wire.Bind(new(service.LBRegistryReloader), new(*loadbalancer.Registry)), wire.Bind(new(service.GroupRegistryReloader), new(*loadbalancer.Registry)), wire.Bind(new(handler.RegistryHelper), new(*loadbalancer.Registry)), loadbalancer.NewDynamicLoadBalancer, wire.Bind(new(loadbalancer.LoadBalancer), new(*loadbalancer.DynamicLoadBalancer)), newAsyncMetricsCollector, wire.Bind(new(loadbalancer.MetricsCollector), new(*loadbalancer.AsyncMetricsCollector)))

func newAsyncMetricsCollector(reg *loadbalancer.Registry) *loadbalancer.AsyncMetricsCollector {
	return loadbalancer.NewAsyncMetricsCollector(reg, 1024)
}

var serviceSet = wire.NewSet(service.NewService, service.NewAIModelService, service.NewChannelService, service.NewChannelGroupService, service.NewTokenService, service.NewUserService, service.NewSystemConfigService, service.NewRelayService, service.NewStatsService, wire.Bind(new(handler.StatsService), new(*service.StatsService)), service.NewRequestLogService, wire.Bind(new(service.RequestLogService), new(*service.RequestLogServiceImpl)), wire.Bind(new(service.RequestLogCreator), new(*service.RequestLogServiceImpl)))

var handlerSet = wire.NewSet(handler.NewHandler, handler.NewModelHandler, handler.NewChannelHandler, handler.NewChannelGroupHandler, handler.NewTokenHandler, handler.NewUserHandler, handler.NewSystemConfigHandler, handler.NewStatsHandler, handler.NewRelayHandler, handler.NewRequestLogHandler, handler.NewDebugHelperHandler)

var serverSet = wire.NewSet(server.NewHttpServer, server.NewMigrate)

var taskSet = wire.NewSet(tasks.NewMockTask, tasks.NewStatsAggregationTask)

func NewTaskServer(
	logger *log.Logger,
	mockTask *tasks.MockTask,
	statsAggregationTask *tasks.StatsAggregationTask,
) *task.TaskServer {
	return task.NewTaskServer(logger, mockTask, statsAggregationTask)
}

func newApp(
	httpServer *http.Server,
	taskServer *task.TaskServer,
) *app.App {
	return app.NewApp(app.WithServer(httpServer, taskServer), app.WithName("tudou"))
}
